import type { Doc } from "@/convex/_generated/dataModel";
import { ProspectCard } from "@/features/prospects/ui/components/prospect-card/ProspectCard";
import {
  getWorkspaceUseCase,
  type WorkspaceUseCaseKey,
} from "@/shared/lib/workspaceUseCases";

export function SetupExampleProfiles({
  profiles,
  useCaseKey,
}: {
  profiles: NonNullable<Doc<"workspaces">["icps"]>;
  useCaseKey: WorkspaceUseCaseKey;
}) {
  const labels = getWorkspaceUseCase(useCaseKey);
  return (
    <section className="space-y-4 px-4 py-4">
      <p className="text-muted-foreground text-sm text-pretty">
        These are{" "}
        <span className="text-foreground">
          example {labels.entityPlural.toLowerCase()}
        </span>{" "}
        generated by the Agent to steer it in the{" "}
        <span className="text-foreground">right direction</span>.{" "}
        <span className="text-foreground">Continue if these look right.</span>
      </p>
      <div className="flex flex-col gap-3">
        {profiles.flatMap((profile) =>
          (profile.syntheticExamples ?? []).map((example) => (
            <ProspectCard
              key={`${profile.title}:${example.platform}`}
              prospect={{
                synthetic: true,
                displayName: example.displayName,
                title: example.title,
                briefIntro: example.bio,
                platform: example.platform,
                prospectType: "individual",
              }}
              interactive={false}
              showMenu={false}
              entityLabel={labels.entitySingular}
            />
          ))
        )}
      </div>
    </section>
  );
}
