allowBuilds:
  core-js: false
  esbuild: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  "@xdevplatform/chat-xdk@0.5.0": patches/@xdevplatform__chat-xdk@0.5.0.patch
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
