// @vitest-environment happy-dom
import { expect, test, vi } from "vitest";
import { guardPlaybackKeyboard } from "../../../../../demos/app/runtime/playbackInputHelpers";

for (const mobile of [true, false]) {
  test(`scripted keyboard guard preserves real editing and original input modes (touch=${mobile})`, async () => {
    const media = {
      matches: mobile,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
    } as unknown as MediaQueryList;
    const host = document.createElement("div");
    host.innerHTML =
      '<input inputmode="email"><textarea></textarea><div contenteditable="true"></div><div contenteditable></div><div contenteditable="plaintext-only"></div>';
    document.body.append(host);
    const guard = guardPlaybackKeyboard(document, media);
    try {
      const input = host.querySelector("input")!;
      const textarea = host.querySelector("textarea")!;
      expect(input.inputMode).toBe(mobile ? "none" : "email");
      expect(textarea.getAttribute("inputmode")).toBe(mobile ? "none" : null);
      for (const editor of host.querySelectorAll("[contenteditable]"))
        expect(editor.getAttribute("inputmode")).toBe(mobile ? "none" : null);
      const added = document.createElement("input");
      host.append(added);
      await new Promise((resolve) => setTimeout(resolve, 0));
      expect(added.getAttribute("inputmode")).toBe(mobile ? "none" : null);
      guard.release(new PointerEvent("pointerdown"));
      expect(input.inputMode).toBe(mobile ? "none" : "email");
      // Trusted events can only be generated by a browser; test the policy here,
      // then exercise real pointer events in the browser regression test.
      guard.release({ isTrusted: true, type: "wheel" } as Event);
      expect(input.inputMode).toBe(mobile ? "none" : "email");
      input.focus();
      guard.release({ isTrusted: true, type: "pointerdown" } as Event);
      expect(input.inputMode).toBe("email");
      expect(textarea.hasAttribute("inputmode")).toBe(false);
      if (mobile) expect(document.activeElement).not.toBe(input);
      guard.suppress();
      expect(input.inputMode).toBe(mobile ? "none" : "email");
      guard.release({ isTrusted: true, type: "keydown" } as Event);
      expect(input.inputMode).toBe("email");
      guard.suppress();
    } finally {
      guard.dispose();
      expect(host.querySelector("input")!.inputMode).toBe("email");
      expect(host.querySelector("textarea")!.hasAttribute("inputmode")).toBe(
        false
      );
      host.remove();
    }
  });
}
